#!/bin/bash

# Ghostarch Installer - Main Entry Point
# WSL2 Arch Linux setup with BlackArch tools
#
# This script:
#   1. Installs core (zsh, oh-my-zsh, BlackArch repo)
#   2. Creates user and workspace
#   3. Sets default shell to zsh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="${SCRIPT_DIR}/scripts"

source "${SCRIPTS_DIR}/lib/common.sh"
source "${SCRIPTS_DIR}/lib/users.sh"

NONINTERACTIVE="${NONINTERACTIVE:-0}"
DEBUG="${DEBUG:-0}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) usage ;;
        -n|--noninteractive) NONINTERACTIVE=1 ;;
        -d|--debug) DEBUG=1 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
    shift
done

setup_zsh() {
    echo
    log_info "=== Setting Up Zsh ==="
    
    if command -v zsh &>/dev/null; then
        log_info "Setting zsh as default shell..."
        
        if [[ "$TARGET_USER" == "$(whoami)" ]]; then
            chsh -s /bin/zsh 2>/dev/null || log_warn "Failed to set zsh as default shell"
        else
            sudo chsh -s /bin/zsh "$TARGET_USER" 2>/dev/null || log_warn "Failed to set zsh for user $TARGET_USER"
        fi
        
        log_info "Zsh set as default shell"
    else
        log_warn "Zsh not installed, skipping shell change"
    fi
}

setup_zshrc() {
    echo
    log_info "=== Configuring Zsh RC ==="
    
    local zshrc_template="${SCRIPT_DIR}/templates/zshrc"
    local user_home
    local user_zshrc
    
    if [[ "$TARGET_USER" == "$(whoami)" ]]; then
        user_home="$HOME"
    else
        user_home=$(getent passwd "$TARGET_USER" | cut -d: -f6)
    fi
    
    user_zshrc="${user_home}/.zshrc"
    
    if [[ -f "$zshrc_template" ]]; then
        if [[ -f "$user_zshrc" ]]; then
            log_info "Backing up existing .zshrc to .zshrc.backup"
            cp "$user_zshrc" "${user_zshrc}.backup" 2>/dev/null || sudo cp "$user_zshrc" "${user_zshrc}.backup"
        fi
        
        log_info "Merging zshrc template to $user_zshrc"
        
        # Create header
        cat > "$user_zshrc" << 'HEADER'
# ============================================
# Ghostarch Zsh Configuration
# Generated by install-ghostarch.sh
# ============================================

HEADER
        
        # Append template content
        cat "$zshrc_template" >> "$user_zshrc"
        
        # Set ownership
        if [[ "$TARGET_USER" != "$(whoami)" ]]; then
            sudo chown "$TARGET_USER:$TARGET_USER" "$user_zshrc" 2>/dev/null || true
        fi
        
        log_info "Zshrc configured successfully"
    else
        log_warn "Zshrc template not found at $zshrc_template"
    fi
}

configure_wsl_default_user() {
    echo
    log_info "=== Configuring WSL Default User ==="
    
    if [[ -f /proc/version ]] && grep -qi microsoft /proc/version; then
        local wsl_conf="/etc/wsl.conf"
        
        if [[ -f "$wsl_conf" ]]; then
            if grep -q "default=$TARGET_USER" "$wsl_conf" 2>/dev/null; then
                log_info "WSL already configured for user: $TARGET_USER"
                return 0
            fi
            local backup
            backup="${wsl_conf}.backup.$(date +%Y%m%d%H%M%S)"
            cp "$wsl_conf" "$backup"
            log_info "Backed up existing wsl.conf to $backup"
        fi
        
        log_info "Configuring WSL to default to user: $TARGET_USER"
        
        cat > "$wsl_conf" << EOF
[user]
default=$TARGET_USER
EOF
        
        log_info "WSL default user configured"
        echo
        echo "IMPORTANT: Please run these commands in Windows PowerShell to apply:"
        echo "  wsl --terminate ArchLinux"
        echo "  wsl -d ArchLinux"
        echo "This will restart WSL and apply the new default user."
    else
        log_info "Not running in WSL, skipping WSL configuration"
    fi
}

main() {
    init_logging
    
    echo "============================================"
    echo "  Ghostarch Installer v1.0.0"
    echo "  Custom Arch WSL2 with BlackArch Tools"
    echo "============================================"
    echo
    
    if [[ "$NONINTERACTIVE" == "1" ]]; then
        export NONINTERACTIVE=1
    fi
    
    if [[ "$DEBUG" == "1" ]]; then
        export DEBUG=1
    fi
    
    echo "Step 1: Core Installation (zsh, oh-my-zsh, BlackArch)"
    echo "--------------------------------------------------------"
    "$SCRIPTS_DIR/install-core.sh" "$@"
    
    echo
    echo "Step 2: User & Workspace Setup"
    echo "--------------------------------------------------------"
    prompt_user_setup
    prompt_workdir_setup
    setup_zsh
    setup_zshrc
    configure_wsl_default_user
    
    echo
    echo "============================================"
    echo "  Installation Complete!"
    echo "============================================"
    echo
    echo "Summary:"
    echo "  User: $TARGET_USER"
    echo "  Working Directory: $WORKDIR"
    echo "  Default Shell: zsh"
    echo
    echo "IMPORTANT: Restart WSL to apply user changes:"
    echo "  wsl --terminate ArchLinux"
    echo "  wsl -d ArchLinux"
    echo
    echo "Next steps:"
    echo "  - Run ./scripts/install-tools.sh to install tools"
    echo "  - Run ./scripts/install-nvidia.sh for GPU acceleration (optional)"
    echo
    
    log_info "Installation completed successfully!"
}

main "$@"
