#!/bin/bash

# Ghostarch Installer - Main Entry Point
# WSL2 Arch Linux setup with BlackArch tools

set -euo pipefail

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}"

# Source common library
if [[ -f "${PROJECT_ROOT}/lib/common.sh" ]]; then
    source "${PROJECT_ROOT}/lib/common.sh"
else
    echo "Error: Could not find ${PROJECT_ROOT}/lib/common.sh"
    exit 1
fi

usage() {
    cat << EOF
Ghostarch Installer - Main Entry Point

USAGE:
    $0 [OPTIONS]

OPTIONS:
    -h, --help              Show this help message
    -n, --noninteractive   Run in non-interactive mode
    -d, --debug            Enable debug output

EXAMPLES:
    $0                      # Interactive installation
    $0 --noninteractive     # Non-interactive (use defaults)

MODULAR USAGE:
    ./install-core.sh    # Core only
    ./install-tools.sh   # Tools only
    ./install-nvidia.sh # GPU acceleration

EOF
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) usage ;;
        -n|--noninteractive) export NONINTERACTIVE=1 ;;
        -d|--debug) export DEBUG=1 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
    shift
done

setup_zsh_shell() {
    echo
    log_info "=== Setting Up Zsh Shell ==="
    
    if command -v zsh &>/dev/null; then
        log_info "Setting zsh as default shell for $TARGET_USER..."
        
        if [[ "$TARGET_USER" == "$(whoami)" ]]; then
            sudo chsh -s /bin/zsh "$(whoami)" 2>/dev/null || log_warn "Failed to set zsh as default shell"
        else
            sudo chsh -s /bin/zsh "$TARGET_USER" 2>/dev/null || log_warn "Failed to set zsh for user $TARGET_USER"
        fi
        
        log_info "Zsh set as default shell"
    else
        log_warn "Zsh not installed, skipping shell change"
    fi
}

setup_zshrc() {
    echo
    log_info "=== Configuring Zsh RC ==="
    
    local zshrc_template="${PROJECT_ROOT}/templates/zshrc"
    local user_home
    local user_zshrc
    
    if [[ "$TARGET_USER" == "$(whoami)" ]]; then
        user_home="$HOME"
    else
        user_home=$(getent passwd "$TARGET_USER" | cut -d: -f6)
    fi
    
    user_zshrc="${user_home}/.zshrc"
    
    if [[ -f "$zshrc_template" ]]; then
        if [[ -f "$user_zshrc" ]]; then
            log_info "Backing up existing .zshrc to .zshrc.backup"
            sudo cp "$user_zshrc" "${user_zshrc}.backup" 2>/dev/null || true
        fi
        
        log_info "Applying zshrc template to $user_zshrc"
        
        # Create new zshrc with header
        sudo bash -c "cat > '$user_zshrc'" << 'HEADER'
# ============================================
# Ghostarch Zsh Configuration
# Generated by install-ghostarch.sh
# ============================================

HEADER
        
        # Append template content
        sudo bash -c "cat '$zshrc_template' >> '$user_zshrc'"
        
        # Set ownership
        sudo chown "$TARGET_USER:$TARGET_USER" "$user_zshrc" 2>/dev/null || true
        
        log_info "Zshrc configured successfully"
    else
        log_warn "Zshrc template not found at $zshrc_template"
    fi
}

configure_wsl_default_user() {
    echo
    log_info "=== Configuring WSL Default User ==="
    
    if [[ -f /proc/version ]] && grep -qi microsoft /proc/version; then
        local wsl_conf="/etc/wsl.conf"
        
        log_info "Configuring WSL to default to user: $TARGET_USER"
        
        sudo bash -c "cat > '$wsl_conf'" << EOF
[user]
default=$TARGET_USER
EOF
        
        log_info "WSL default user configured"
        echo
        echo "IMPORTANT: Please run these commands in Windows PowerShell to apply:"
        echo "  wsl --terminate ArchLinux"
        echo "  wsl -d ArchLinux"
        echo "This will restart WSL and apply the new default user."
    else
        log_info "Not running in WSL, skipping WSL configuration"
    fi
}

main() {
    init_logging
    
    echo "============================================"
    echo "  Ghostarch Installer v${GHOSTARCH_VERSION}"
    echo "  Custom Arch WSL2 with BlackArch Tools"
    echo "============================================"
    echo
    
    check_root
    check_wsl
    check_sudo
    load_config
    
    echo "Step 1: Core Installation (zsh, oh-my-zsh, BlackArch)"
    echo "--------------------------------------------------------"
    "${PROJECT_ROOT}/install-core.sh" "$@"
    
    echo
    echo "Step 2: User & Workspace Setup"
    echo "--------------------------------------------------------"
    prompt_user_setup
    prompt_workdir_setup
    setup_zsh_shell
    setup_zshrc
    configure_wsl_default_user
    
    echo
    echo "============================================"
    echo "  Installation Complete!"
    echo "============================================"
    echo
    echo "Summary:"
    echo "  User: $TARGET_USER"
    echo "  Working Directory: $WORKDIR"
    echo "  Default Shell: zsh"
    echo
    echo "IMPORTANT: Restart WSL to apply user changes:"
    echo "  wsl --terminate ArchLinux"
    echo "  wsl -d ArchLinux"
    echo
    echo "Next steps:"
    echo "  - Run ./install-tools.sh to install tools"
    echo "  - Run ./install-nvidia.sh for GPU acceleration (optional)"
    echo
    
    log_info "Installation completed successfully!"
}

main "$@"
