#!/bin/bash

# Ghostarch Zsh Configuration
# Zsh shell setup and configuration functions

setup_zsh_shell() {
    echo
    log_info "=== Setting Up Zsh Shell ==="

    if command -v zsh &>/dev/null; then
        log_info "Setting zsh as default shell for $TARGET_USER..."

        if [[ "$TARGET_USER" == "$(whoami)" ]]; then
            sudo chsh -s /bin/zsh "$(whoami)" 2>/dev/null || log_warn "Failed to set zsh as default shell"
        else
            sudo chsh -s /bin/zsh "$TARGET_USER" 2>/dev/null || log_warn "Failed to set zsh for user $TARGET_USER"
        fi

        log_info "Zsh set as default shell"
    else
        log_warn "Zsh not installed, skipping shell change"
    fi
}

setup_zshrc() {
    echo
    log_info "=== Configuring Zsh RC ==="

    local zshrc_template="${PROJECT_ROOT}/templates/zshrc"
    local user_home
    local user_zshrc

    if [[ "$TARGET_USER" == "$(whoami)" ]]; then
        user_home="$HOME"
    else
        user_home=$(getent passwd "$TARGET_USER" | cut -d: -f6)
    fi

    user_zshrc="${user_home}/.zshrc"

    if [[ -f "$zshrc_template" ]]; then
        if [[ -f "$user_zshrc" ]]; then
            log_info "Backing up existing .zshrc to .zshrc.backup"
            sudo cp "$user_zshrc" "${user_zshrc}.backup" 2>/dev/null || true
        fi

        log_info "Applying zshrc template to $user_zshrc"

        sudo bash -c "cat > '$user_zshrc'" <<'HEADER'
# ============================================
# Ghostarch Zsh Configuration
# Generated by install-ghostarch.sh
# ============================================

HEADER

        sudo bash -c "cat '$zshrc_template' >> '$user_zshrc'"

        sudo chown "$TARGET_USER:$TARGET_USER" "$user_zshrc" 2>/dev/null || true

        log_info "Zshrc configured successfully"
    else
        log_warn "Zshrc template not found at $zshrc_template"
    fi
}

configure_wsl_default_user() {
    echo
    log_info "=== Configuring WSL Default User ==="

    if [[ -f /proc/version ]] && grep -qi microsoft /proc/version; then
        local wsl_conf="/etc/wsl.conf"

        log_info "Configuring WSL to default to user: $TARGET_USER"

        sudo bash -c "cat > '$wsl_conf'" <<EOF
[user]
default=$TARGET_USER
EOF

        log_info "WSL default user configured"
        echo
        echo "IMPORTANT: Please run these commands in Windows PowerShell to apply:"
        echo "  wsl --terminate ArchLinux"
        echo "  wsl -d ArchLinux"
        echo "This will restart WSL and apply the new default user."
    else
        log_info "Not running in WSL, skipping WSL configuration"
    fi
}
